// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppGSL.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_gen_angle
arma::vec rcpp_gen_angle();
RcppExport SEXP _tRexCAP_rcpp_gen_angle() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_gen_angle());
    return rcpp_result_gen;
END_RCPP
}
// Rx
arma::mat Rx(double theta);
RcppExport SEXP _tRexCAP_Rx(SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(Rx(theta));
    return rcpp_result_gen;
END_RCPP
}
// Ry
arma::mat Ry(double theta);
RcppExport SEXP _tRexCAP_Ry(SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(Ry(theta));
    return rcpp_result_gen;
END_RCPP
}
// Rz
arma::mat Rz(double theta);
RcppExport SEXP _tRexCAP_Rz(SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(Rz(theta));
    return rcpp_result_gen;
END_RCPP
}
// dist_trans
arma::mat dist_trans(const arma::vec& phi, const arma::mat& x, const arma::mat& y);
RcppExport SEXP _tRexCAP_dist_trans(SEXP phiSEXP, SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(dist_trans(phi, x, y));
    return rcpp_result_gen;
END_RCPP
}
// beta_func
double beta_func(double beta, const arma::mat& llambdax, const arma::mat& y12, const arma::mat& ddd);
RcppExport SEXP _tRexCAP_beta_func(SEXP betaSEXP, SEXP llambdaxSEXP, SEXP y12SEXP, SEXP dddSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type llambdax(llambdaxSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y12(y12SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ddd(dddSEXP);
    rcpp_result_gen = Rcpp::wrap(beta_func(beta, llambdax, y12, ddd));
    return rcpp_result_gen;
END_RCPP
}
// r_zeroin2
arma::vec r_zeroin2(double a, double b, const arma::mat& llambdax, const arma::mat& y12, const arma::mat& ddd, double tol, int Maxit);
RcppExport SEXP _tRexCAP_r_zeroin2(SEXP aSEXP, SEXP bSEXP, SEXP llambdaxSEXP, SEXP y12SEXP, SEXP dddSEXP, SEXP tolSEXP, SEXP MaxitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type llambdax(llambdaxSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y12(y12SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ddd(dddSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type Maxit(MaxitSEXP);
    rcpp_result_gen = Rcpp::wrap(r_zeroin2(a, b, llambdax, y12, ddd, tol, Maxit));
    return rcpp_result_gen;
END_RCPP
}
// project_func
arma::vec project_func(const arma::vec& a, const arma::mat& bounds);
RcppExport SEXP _tRexCAP_project_func(SEXP aSEXP, SEXP boundsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type bounds(boundsSEXP);
    rcpp_result_gen = Rcpp::wrap(project_func(a, bounds));
    return rcpp_result_gen;
END_RCPP
}
// nll
double nll(const arma::vec& phi, const arma::mat& u, const arma::mat& v, const arma::mat& llambdax, const arma::mat& y12);
RcppExport SEXP _tRexCAP_nll(SEXP phiSEXP, SEXP uSEXP, SEXP vSEXP, SEXP llambdaxSEXP, SEXP y12SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type u(uSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type v(vSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type llambdax(llambdaxSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y12(y12SEXP);
    rcpp_result_gen = Rcpp::wrap(nll(phi, u, v, llambdax, y12));
    return rcpp_result_gen;
END_RCPP
}
// grad
arma::vec grad(const arma::vec& phi, const arma::mat& u, const arma::mat& v, const arma::mat& llambdax, const arma::mat& y12);
RcppExport SEXP _tRexCAP_grad(SEXP phiSEXP, SEXP uSEXP, SEXP vSEXP, SEXP llambdaxSEXP, SEXP y12SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type u(uSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type v(vSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type llambdax(llambdaxSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y12(y12SEXP);
    rcpp_result_gen = Rcpp::wrap(grad(phi, u, v, llambdax, y12));
    return rcpp_result_gen;
END_RCPP
}
// APG
arma::vec APG(const arma::mat& y12, const arma::mat& S1, const arma::mat& S2, const arma::mat& llambdax, int T, double tol, double rel_tol);
RcppExport SEXP _tRexCAP_APG(SEXP y12SEXP, SEXP S1SEXP, SEXP S2SEXP, SEXP llambdaxSEXP, SEXP TSEXP, SEXP tolSEXP, SEXP rel_tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y12(y12SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S1(S1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S2(S2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type llambdax(llambdaxSEXP);
    Rcpp::traits::input_parameter< int >::type T(TSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type rel_tol(rel_tolSEXP);
    rcpp_result_gen = Rcpp::wrap(APG(y12, S1, S2, llambdax, T, tol, rel_tol));
    return rcpp_result_gen;
END_RCPP
}
// minimizer
arma::vec minimizer(const uint Nrep, const arma::mat& y12, const arma::mat& S1, const arma::mat& S2, const arma::mat& llambdax, int T, double tol, double rel_tol, int threads);
RcppExport SEXP _tRexCAP_minimizer(SEXP NrepSEXP, SEXP y12SEXP, SEXP S1SEXP, SEXP S2SEXP, SEXP llambdaxSEXP, SEXP TSEXP, SEXP tolSEXP, SEXP rel_tolSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const uint >::type Nrep(NrepSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y12(y12SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S1(S1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S2(S2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type llambdax(llambdaxSEXP);
    Rcpp::traits::input_parameter< int >::type T(TSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type rel_tol(rel_tolSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(minimizer(Nrep, y12, S1, S2, llambdax, T, tol, rel_tol, threads));
    return rcpp_result_gen;
END_RCPP
}
