# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
rcpp_gen_angle <- function() {
    .Call(`_tRexCAP_rcpp_gen_angle`)
}

Rx <- function(theta) {
    .Call(`_tRexCAP_Rx`, theta)
}

Ry <- function(theta) {
    .Call(`_tRexCAP_Ry`, theta)
}

Rz <- function(theta) {
    .Call(`_tRexCAP_Rz`, theta)
}

dist_trans <- function(phi, x, y) {
    .Call(`_tRexCAP_dist_trans`, phi, x, y)
}

beta_func <- function(beta, llambdax, y12, ddd) {
    .Call(`_tRexCAP_beta_func`, beta, llambdax, y12, ddd)
}

r_zeroin2 <- function(a, b, llambdax, y12, ddd, tol = 0.000001, Maxit = 1000L) {
    .Call(`_tRexCAP_r_zeroin2`, a, b, llambdax, y12, ddd, tol, Maxit)
}

project_func <- function(a, bounds) {
    .Call(`_tRexCAP_project_func`, a, bounds)
}

nll <- function(phi, u, v, llambdax, y12) {
    .Call(`_tRexCAP_nll`, phi, u, v, llambdax, y12)
}

grad <- function(phi, u, v, llambdax, y12) {
    .Call(`_tRexCAP_grad`, phi, u, v, llambdax, y12)
}

APG <- function(y12, S1, S2, llambdax, T = 500L, tol = 0.0000001, rel_tol = 0.01) {
    .Call(`_tRexCAP_APG`, y12, S1, S2, llambdax, T, tol, rel_tol)
}

minimizer <- function(Nrep, y12, S1, S2, llambdax, T = 500L, tol = 0.0000001, rel_tol = 0.01, threads = 1L) {
    .Call(`_tRexCAP_minimizer`, Nrep, y12, S1, S2, llambdax, T, tol, rel_tol, threads)
}

