name: Deploy to trex-vignette

on:
  push:
    branches:
      - main
    paths:
      - 'vignettes/tRexCAP.html'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare index.html
        run: |
          mkdir -p deploy
          cp vignettes/tRexCAP.html deploy/index.html

      - name: Deploy to trex-vignette
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.AUTO_SYNC_TOKEN }}
          external_repository: mxw010/trex-vignette
          publish_branch: main
          publish_dir: deploy
          keep_files: false